In [12]:
import numpy as np

#Check the version
print(np.__version__)

2.2.0


In [13]:
# 1-dimensional array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [14]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [15]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [16]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [17]:
a1

array([1, 2, 3])

In [18]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), columns=['a', 'b', 'c'])
df

a  b  c
0  3  0  1
1  9  9  4
2  1  5  5
3  6  1  3
4  1  5  0

In [21]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [22]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])