In [1]:
import numpy as np
print(np.__version__)

2.2.0


## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 2, 4, 9, 8],
       [7, 2, 8, 3, 0],
       [7, 1, 7, 8, 9]], dtype=int32)

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [35]:
random_array_2 = np.random.random((2, 4))
random_array_2

array([[0.85173359, 0.5197286 , 0.26319423, 0.17470627],
       [0.69339087, 0.90799544, 0.55826589, 0.77446338]])

In [36]:
random_array_2.size, random_array_2.shape

(8, (2, 4))

In [38]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.32859639, 0.03355604, 0.81937978],
       [0.14264958, 0.58034974, 0.6379343 ],
       [0.18180738, 0.57705664, 0.80903982],
       [0.78130597, 0.69993213, 0.33482222],
       [0.03183823, 0.12095675, 0.41745383]])

In [47]:
# Pseudo-random numbers
# np.random.seed()
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [59]:
np.random.seed(seed=2)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])

In [64]:
np.random.seed(seed=2)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])